#!/bin/bash

echo -e "\nexposing current folder to local network"
echo "you can reach it on any device at http://$(ip address show wlp3s0| grep -oP '(?<=inet\s)\d+(\.\d+){3}'):8080 "
echo -e "\n"
npx markserv -p 8080 -a 0.0.0.0

